version: '3.8'

services:
  nodejs:
    build: .
    container_name: nodejs-app
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - app-network
    expose:
      - "8000"

  nginx:
    image: nginx:latest
    container_name: nginx-container
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/usr/share/nginx/html
    depends_on:
      - nodejs
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
